### ISSUE TITLE
Error parsing API response for fetch

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/x-api#108]
I've gotten a few of these lately when executing `exercism f`:

```
2016/05/01 07:16:29 error parsing API response - invalid character '<' looking for beginning of value
```

It's not every time, and I've never had it happen twice in a row. I'd say it's roughly 5-10% over the past 3-4 days.

I currently have the exercism CLI v2.2.1.

I will start fetching with `--verbose` and report back if I get more information.

**Comment by NobbZ** [comment]
I have this whenever I fetch without specifying the track. Everytime. I
will try to give more feedback about this when back home and not on mobile
anymore.

Ryan Hartlage <notifications@github.com> schrieb am So., 1. Mai 2016, 13:20:

**Comment by kytrinyx** [comment]
Ahhh, thanks so much for reporting this. This is a problem with a 500 error being returned with an HTML response rather than a JSON response. I'll start hunting this down.

**Comment by kytrinyx** [comment]
Wow, @NobbZ, this is literally timing out. I suspect that the response is too big. I've decided to change the way that the fetch API works. Up until now it returns everything that you have submitted, plus one more exercise.

I think the right thing to do is only return the next exercise. If people want to fetch old exercises, they can do so by using the fully specified command, `exercism fetch TRACK SLUG`.

**Comment by ryanplusplus** [comment]
@kytrinyx sounds about right. My fetch has gotten slower and slower as time has gone on.

**Comment by kytrinyx** [comment]
I'm deploying a fix. Would you keep an eye on this and see if it's still a problem?

**Comment by ryanplusplus** [comment]
Sure. My fetch takes forever, so let me know once it's deployed and I should be able to tell you right away if it's significantly faster or not.

**Comment by ryanplusplus** [comment]
I've done a few fetches without error. They're taking ~10 seconds now which is down from ~30 seconds before.

**Comment by kytrinyx** [comment]
10 seconds is still super, super slow. I have another suspicion about what is going on here... let me collapse from my day and then think about it for a bit.

**Comment by NobbZ** [comment]
I have about 10 seconds wall-time as well. Even if it is very slow for what
actually happes from my point of view (no new exercises), it is much faster
than before.

Katrina Owen <notifications@github.com> schrieb am Di., 3. Mai 2016 um
02:45 Uhr:

**Comment by kytrinyx** [comment]
OK, I've been rethinking a few things. I know what's wrong, and after deciding how to fix it (totally possible) I realized that I don't care enough about the feature that the slowness is supporting. I'm going to tear it out and rethink it from the ground up.

Would you check whether or not this speeds things up?

**Comment by ryanplusplus** [comment]
Just checked, it's now 0.7 seconds. Much improved :)

**Comment by kytrinyx** [comment]
Haha, yeah a bit. Yay!
