### ISSUE TITLE
Serve track icon images with basic track data

### ISSUE THREAD

**Issue by joeltaylor** [exercism/x-api#111]
There's currently an issue over in exercism.io to remove track images from the repo to their respected track repos (https://github.com/exercism/exercism.io/issues/2925).  The image should be either a `png` or an `svg`.

**Comment by kytrinyx** [comment]
> The image should be either a png or an svg.

The image is a PNG, but I'd eventually like to have SVGs instead. See https://github.com/exercism/exercism.io/issues/2910

I was going to post one issue to each track using blazon, which would create the todo list automatically in the parent issue, and it would spread the work out. I haven't had time to catch up with things lately, though.

**Comment by joeltaylor** [comment]
Just updated the PR that can serve both file types, but I can remove the SVG bit?

Oh, didn't know about blazon. Should I go ahead and remove those todos?

**Comment by kytrinyx** [comment]
Let's get that blazon issue created first :)

Nah, let's keep the SVG bit—I really do want to have that.

**Comment by kytrinyx** [comment]
OK, I've sent the blazon thing. Feel free to delete the todo list here.

**Comment by joeltaylor** [comment]
Cool, that'll make things much easier :grin:
