### ISSUE TITLE
For tracks with test generators: Should there be a better way to ignore the generator files?

### ISSUE THREAD

**Issue by petertseng** [exercism/x-api#113]
I know that Ruby and Go have test generators. Sometimes, we want to put files in the `exercises/:slug` directories for various reasons. But we wouldn't want these files to get served to students. We have to use the somewhat hacky way of putting `example` in any generator-related filename to achieve that. That's the most usable ignored pattern in ~~https://github.com/exercism/x-api/blob/master/lib/xapi/implementation.rb~~ https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb.

[Ruby example](https://github.com/exercism/xruby/tree/master/exercises/leap): has example.tt in exercise dir. (Also has other files outside: https://github.com/exercism/xruby/blob/master/bin/generate-leap and https://github.com/exercism/xruby/blob/master/lib/leap_cases.rb, but they do not fall into the category under discussion)

[Go example](https://github.com/exercism/xgo/tree/master/exercises/leap): has example_gen.go in exercise dir.

With a mind to implement some form of generator for other tracks, I wonder if we can have something that is more indicative of a generator (since the generator-related files aren't really examples!). There are some possible options I can think of so I want to discuss here.
1. We discuss and decide a new pattern that gets ignored like `example` does. Perhaps `autogen` or something like that (`gen` seems too likely to have false positives). This is pretty easy to implement and the only requirement is discussion and agreement on what the pattern should be.
2. We allow each track to configure custom patterns in config.json that won't get served to students. This is obviously more work but gives each track a lot of flexibility in how they want to structure things. This may or may not overlap with the `ignored` key that [configlet already uses](https://github.com/exercism/configlet/blob/faaa61542706553b45869ad8fb5b41e22f432aed/configlet/config.go#L18) (but that x-api does not use in any way, far as I can tell). Note that this existing key tells configlet "it's OK if a directory with this exact name exists but isn't in config.json in the exercises list)", seemingly a different concept than what is here. So we may have to come up with a different name than "ignored", or else reconcile the differences.
3. No action required here in x-api. Recommend to tracks that they place their generators outside the `exercises` directory. For example, maybe it's:

```
├── exercises
│   ├── hello-world
│   └── leap
└── generators
    ├── hello-world
    └── leap
```

The only disadvantage might be if track maintainers find it too cumbersome to maintain two corresponding directory trees, otherwise this is pretty flexible and is made possible by the fact that exercises can be moved to the `exercises` directory. I may recommend this approach personally. This approach is not mutually exclusive with either of the above options - it may be decided to do one of the above if a track decides this approach is disadvantageous for some reason.

**Comment by kytrinyx** [comment]
> We discuss and decide a new pattern that gets ignored like example does. Perhaps autogen

This sounds like the easiest approach—it would mean implementing it in one place, and we could put all the files for an exercise (including the generators) in one place.

I also like the separate tree, but it feels a little bit heavy. I'd be curious to hear what others think.

**Comment by Insti** [comment]
I'd like to see the generators living under the exercises & the api can just ignore subdirectories.
```
└── exercises
    ├── hello-world
    │   └── generator
    │   └── solutions
    └── leap
        └── generator
        └── solutions

```
(I'd also like to enable multiple solutions to be called something sensible like `hello_word_golfed.eb` `hello_world_best_practices.rb` rather than `example.rb` as a way of being able to document different approaches to solving a problem but that may be off-topic here.)

**Comment by kytrinyx** [comment]
> that may be off-topic here

That's an interesting approach to it. There's an epic discussion about the topic in https://github.com/exercism/exercism.io/issues/2803 - would you post that suggestion there?

> I'd like to see the generators living under the exercises & the api can just ignore subdirectories.

I like that.

**Comment by jtigger** [comment]
How about filtering any file whose path contains more than zero path parts that (start with '.' and length > 2)?

served:
./hello-world/src/test/java/HelloWorldTest.java
./hello-world/src/main/java/HelloWorld.java

filtered:
./hello-world/src/.examples/java/HelloWorld.java
./hello-world/src/.testgen/java/GenHelloWorldTest.java
./hello-world/src/main/java/.todo.txt

**Comment by NobbZ** [comment]
@jtigger What exactly do you mean by "length > 2"? I do not see any sense in serving ".f" but not ".foo", either serve all or none dotted files/folders.

**Comment by jtigger** [comment]
Yeah, no.  Scratch that part.  I should have just said, "any path part that starts with a dot."

**Comment by kytrinyx** [comment]
We've explicitly included files starting with dots. There was a bug at some point where these files were excluded, and we apparently need them. I don't recall which track(s) use this.

**Comment by jtigger** [comment]
Well that's a bummer.  Was hoping to leverage the fact that these are hidden files in *nix OSes. :-/

* a number of tracks use `.keep` files to ensure the directory is delivered (notably, `kotlin`, `java`, and `scala`
* `ocaml` includes `.merlin` files
* `ruby` and `powershell` include `.version` files
* `haxe` includes a few `.munit` files

**Comment by kytrinyx** [comment]
I don't think `.keep` matters. In Ruby we use `.version` for the generated tests, so I think that's fine. I'm not sure whether Powershell uses them for a different purpose.

Maybe it was haxe or ocaml. Or maybe I dreamt it.

**Comment by jtigger** [comment]
Same concept: a double-underscore?

```
./poker/__example.rb
./hello-world/src/__testgen/java/GenHelloWorldTest.java
./leap/__generator/...
```

right now, in x-api:
```
$ find tracks -path "__*" | wc -l
       0
```

**Comment by kytrinyx** [comment]
> Same concept: a double-underscore?

Love it, @jtigger!

**Comment by jtigger** [comment]
Question: would you want to replace the "example" filter with this one? or filter out both patterns?

**Comment by kytrinyx** [comment]
I'm not sure. I'm worried that we'd run into language-specific snarls, and would rather filter out both patterns.

**Comment by Insti** [comment]
How about just a single directory called `meta` or `.meta` to exclude? It could contain all the meta stuff like example solutions and generators, and everything else can be returned as the exercise files.

**Comment by kytrinyx** [comment]
I like the `.meta` suggestion, @Insti.

**Comment by jtigger** [comment]
I like it too.  I was trying to come up with a general approach (especially being able to mark individual files, regardless of location).  But honestly, I can't come up with a real world use-case.

I like that `.meta` says what it is.  (rather than something like `.skip` (i.e. opposite of `.keep`) which says how it should be treated.

**Comment by petertseng** [comment]
Closed by https://github.com/exercism/trackler/pull/4

**Comment by petertseng** [comment]
> We allow each track to configure custom patterns in config.json that won't get served to students.

This was done in https://github.com/exercism/trackler/pull/33.

**Comment by Insti** [comment]
This should probably be documented somewhere. Where is the right place?

**Comment by Insti** [comment]
It probably should be where the `<track>/config.json` file is documented, but I cannot find that.

**Comment by kytrinyx** [comment]
We've got smatterings of documentation spread out in several places. We're totally missing an actual bit of documentation about the config.json.

I opened an issue about documenting it: https://github.com/exercism/docs/issues/12
