### ISSUE TITLE
[Discussion] Automate updation of submodules

### ISSUE THREAD

**Issue by tejasbubane** [exercism/x-api#114]
Looks like @kytrinyx has to manually update submodules regularly (ref: https://github.com/exercism/xcrystal/pull/21). I was just wondering if we can automate this process so that she doesn't have to remember to do it.

We can have a cron-like thing (using something like [heroku-sceduler](https://devcenter.heroku.com/articles/scheduler)). Just an idea - not sure how feasible this is.

**Comment by kytrinyx** [comment]
I would love to do this. My problem at the moment is that sometimes people commit things to the tracks that break things.

I guess the right thing to do would be to figure out how to add tests every time a new and exciting way to break the API is discovered, and then only deploy if the tests pass (and perhaps send an email or auto-post an issue or something if they fail).

I'll open a new issue to add a test for the thing that broke yesterday :)

**Comment by kytrinyx** [comment]
For reference, my current, manual process is this:

- `git submodule foreach git pull origin master`
- run the tests, run the config verification, run the metadata verification
- `git commit -m "Update submodules"`
- `git push origin master && git push heroku master`

I do have shortcuts for things, but it's still manual.

**Comment by kytrinyx** [comment]
> I'll open a new issue to add a test for the thing that broke yesterday :)

And don't you know I already had that test, but on my new system I wasn't set up to automatically run it. Sheesh.

**Comment by tejasbubane** [comment]
I don't think we have an automation solution. Also the submodules have been [moved to `trackler` now](https://github.com/exercism/trackler/tree/master/tracks). I guess I should give this a close. If we think of a solution or want to discuss, we should create an issue in trackler instead.

**Comment by kytrinyx** [comment]
I've mostly automated this. I have a script that I have to kick off which updates and deploys everything.

I run it most days (barring complicated travel or personal life making it very difficult to get to a computer).

I don't want to put it on a cron job since it sometimes blows up in unexpected ways. I'm pretty happy with the current level of automation, though.
