### ISSUE TITLE
Tests: Sensitive to local filesystem file ordering.

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#118]
I recently checked out a clean version of the repository.
When I ran the tests 4 failed. 
This was due to file ordering being different.

2 looked ok:
```
diff --git a/test/fixtures/approvals/get_track_fake.approved.json b/test/fixtures/approvals/get_track_f
index ecae415..6ac1beb 100644
--- a/test/fixtures/approvals/get_track_fake.approved.json
+++ b/test/fixtures/approvals/get_track_fake.approved.json
@@ -38,8 +38,8 @@
       "name": "One",
       "files": {
         ".dot": "dot\n",
-        "Fakefile": "Autorun fake code\n",
         "one_test.ext": "assert 'one'\n",
+        "Fakefile": "Autorun fake code\n",
         "sub/src/stubfile.ext": "stub\n",
         "README.md": "# One\n\nThis is one.\n\n* one\n* one again\n\n* one hint\n* one more hint\n\n##
       },
```

```
diff --git a/test/fixtures/approvals/v3_exercise_tests.approved.json b/test/fixtures/approvals/v3_exerc
index 89c52b7..7e445a0 100644
--- a/test/fixtures/approvals/v3_exercise_tests.approved.json
+++ b/test/fixtures/approvals/v3_exercise_tests.approved.json
@@ -6,8 +6,8 @@
     "name": "Dog",
     "blurb": "This is dog.",
     "files": {
-      "a_dog.animal": "assert 'woof woof'\n",
-      "a_dog_2.animal": "assert \"Miaowww\"\n"
+      "a_dog_2.animal": "assert \"Miaowww\"\n",
+      "a_dog.animal": "assert 'woof woof'\n"
     }
   }
 }
```

2 looked a bit scarier (and are the same bug.) returning a different `doc_format`

```
1) Failure:
TrackTest#test_doc_format [/home/geoff/Dev/Exercisim/x-api/test/xapi/track_test.rb:64]:
Expected: "org"
  Actual: "md"
```

```
diff --git a/test/fixtures/approvals/v3_track.approved.txt b/test/fixtures/approvals/v3_track.approved.
index ba0f056..9caddb0 100644
--- a/test/fixtures/approvals/v3_track.approved.txt
+++ b/test/fixtures/approvals/v3_track.approved.txt
@@ -8,7 +8,7 @@
        "todo" => ["banana", "cherry"]
        "active" => true
        "implemented" => true
-       "doc_format" => "org"
+       "doc_format" => "md"
        "docs" => {"about"=>"Language Information\n", "installation"=>"Installing\n", "tests"=>"Running
        "problems" => [{"slug"=>"hello-world", "name"=>"Hello World", "blurb"=>"Oh, hello."}, {"slug"=>
 }
```

**Sugested actions**
1) Ensure that the result of reading a group of files is sorted before further processing. This should ensure that the files are output in a consistent order across machines/OSes/filesystems

2) Work out what [`doc_format`](https://github.com/exercism/x-api/blob/master/lib/xapi/track.rb#L83) is supposed to be doing, because I don't think it's doing the right thing by only checking 1 file unless they are all guaranteed to be the same, (which it's not checking for either.)

**Comment by kytrinyx** [comment]
Yeah, we've run into this before—linux (CI) vs mac (my dev environment).

I tend to fix it by sorting in the tests explicitly.

> Work out what doc_format is supposed to be doing

It's supposed to figure out whether the docs/* are in markdown or orgmode. There are tests for that, but I make no guarantees beyond that.

They're all going to be either 'md' or 'org'. I'm sure at some point we could mistakenly have a mix, but I don't think it's likely.

**Comment by Insti** [comment]
Choose the most popular?
```ruby
  0     def doc_format
  1       formats = Dir.glob(File.join(dir, "docs", "*.*")).map do |filename|
  2         File.extname(filename)
  3       end
  4       formats.max_by { |format| formats.count(format) }
  5     end
```

**Comment by Insti** [comment]
It's currently only(?) used to work out what the name of the file to edit is at the bottom of the track documentation on the exercism.io site.
> Help us explain this better! File a GitHub issue at https://github.com/exercism/xruby/issues if you have suggestions, or submit a patch with improvements to the https://github.com/exercism/xruby/blob/master/docs/INSTALLATION.md file.

**Comment by kytrinyx** [comment]
We also use it to convert the org files to markdown before submitting them to the site via the API, I believe.

**Comment by Insti** [comment]
> We also use it to convert the org files to markdown before submitting them to the site via the API, I believe.

There's a another different bit of code for that :confused:

**Comment by kytrinyx** [comment]
> There's a another different bit of code for that

Ah. Hm. This code base isn't actually terrible, but there sure are some weird corners.

> Choose the most popular?

Yeah, that seems reasonable.
