### ISSUE TITLE
Tests: Coveralls and Simplecov disagree.

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#119]
Coveralls reports 56% coverage.
Simplecov reports 97% coverage.

Why the discrepancy? I suspect the Simplecov figure is correct, and there is something wrong in the Coveralls configuration but have not done enough research yet to be certain of this.

**Comment by kytrinyx** [comment]
We run `- CI=1 bundle exec rake test:each` for CI, and my guess is that test:each doesn't get a good aggregate.

I'm submitting a PR with a suggested change.

**Comment by kytrinyx** [comment]
OK, we'll see if the coverage on that PR looks any better.
