### ISSUE TITLE
Documentation:  Intro to Git submodules.

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#128]
Add an introduction to git submodules.

Submodules are an aspect of git that many people will not have encountered before.
Add some basic documentation about them and how they are used in the x-api repository to Readme.md 

(Or maybe Contributing.md is a better place? - Discuss.)

**Comment by Insti** [comment]
This could be a good first patch **especially** if you don't know anything about git submodules.
Learn about them and write what you just learned!

**Comment by kytrinyx** [comment]
I think it makes sense to put these in the Contributing Guide. It looks like maybe we have some overlap between the README and the Contributing Guide—maybe we need a separate issue to sort that out.
