### ISSUE TITLE
Documentaton: Move track contributing documentation to x-common

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#130]
The `Track Anatomy` section of the [CONTRIBUTING.md](https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#track-anatomy) would be better covered within the x-common repository.

And then the language track READMEs could direct people there, which is now a more useful place than the x-api repository for people interested in language tracks and problems.

**Comment by kytrinyx** [comment]
To clarify, do you mean that this could be moved from the x-api contributing guide to the x-common one?

**Comment by Insti** [comment]
> do you mean that this could be moved from the x-api contributing guide to the x-common one?

Yes.

It is relevant to the x-api code, but x-api already needs to be aware of x-common, and those working on x-common for the most part have no reason to care about the details of what goes on in x-api.
It would be better to refer x-api users to the x-common documentation.

**Comment by kytrinyx** [comment]
Yeah, that makes sense. Let's do it.

**Comment by chischaschos** [comment]
Hi, would these PRs work?. Please let me know if it needs any change or If I misunderstood something.

**Comment by Insti** [comment]
Those look good @chischaschos , Thanks.

**Comment by mixolidia** [comment]
@kytrinyx should this be closed?
