### ISSUE TITLE
Add MIPS submodule

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#131]
I saw something recently that made me think that the MIPS track was ready to go live, but the https://github.com/exercism/xmips repository is not yet included as a git submodule here.

(Maybe that's part of the process? More documentation on this would be nice.)

**Comment by Insti** [comment]
It was added here: https://github.com/exercism/x-api/commit/0534a68e94bae784d9d74b6ad80e89b0b0612c9f

**Comment by Insti** [comment]
Not sure why it wasn't showing up for me, maybe it wasn't pushed yet?

Process documentation is still needed though.

**Comment by kytrinyx** [comment]
> Process documentation is still needed though.

Yeah, definitely.

> Not sure why it wasn't showing up for me, maybe it wasn't pushed yet?

It was live on the site under "upcoming tracks", now it's listed as an active track.
