### ISSUE TITLE
Deprecate "problems" key in config.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#134]
For the past three years, the ordering of exercises has been done based on gut feelings and wild guesses. Over time this has proven to work OK-ish, but it's not great. In order to have the ability to support a more structured and systematic approach to ordering problems, we're going to deprecate the simple array of problem slugs in the `config.json` file of each track, and start using a new format, under the key "exercises", documented below:

```
"exercises": [
      {
        "slug": "hello-world" ,
        "difficulty": 1,
        "topics": [
            "control-flow (if-statements)",
            "optional values",
            "text formatting"
        ]
      },
      {
        "difficulty": 3,
        "slug": "anagram",
        "topics": [
            "strings",
            "filtering"
        ]
      },
      {
        "difficulty": 1,
        "slug": "binary",
        "topics": [
            "parsing",
            "transforming"
        ]
      }
    ]
```

We need to update the x-api so that it can use either format, with a preference for "exercises".

That is to say that where we read the "config.json" file to determine which problems are in a track, and in which order, we should use the order as defined in "exercises". If, however, "exercises" is missing from a config.json, the code should not break. We should fall back to using the "problems" key.

The config.json file is read in [`lib/xapi/track.rb`](https://github.com/exercism/x-api/blob/master/lib/xapi/track.rb#L113).

See https://github.com/exercism/discussions/issues/60 for the full discussion.

**Comment by ramyaravindranath** [comment]
@kytrinyx Looking into this.

**Comment by kytrinyx** [comment]
Addressed in https://github.com/exercism/x-api/pull/137
