### ISSUE TITLE
Support global deprecation of exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#139]
We sometimes decide to stop supporting an exercise.

That means that:

- Each track that has implemented it should add it to the `deprecated` list in the `config.json` file so that it doesn't get delivered automatically when people `exercism fetch` exercises.
- The exercise should not show up in the "to be implemented" list for the other language tracks

In order to do this, we're going to add an empty file named `.deprecated` in the exercise directory of x-common.

It will look like this for a deprecated exercise:

```
$ tree -a exercises/point-mutations/
exercises/point-mutations/
├── .deprecated
├── description.md
└── metadata.yml
```

An exercise that is not deprecated will not have the `.deprecated` file.

In the x-api we will need to make it so that if the `.deprecated` file is there, then the problem will not show up in the "todo" lists.

- [ ] `/api/v1/routes/tracks.rb`: `GET /tracks`
- [ ] `/api/v1/routes/tracks.rb`: `GET /tracks/:id`
- [ ] `api/v3/routes/problems.rb`: `GET /problems/data-todos`
- [ ] `api/v3/routes/problems.rb`: `/problems/:slug/todo`
- [ ] `api/v3/routes/tracks.rb`: `/tracks/:id/todo`
- [ ] `api/v3/routes/tracks.rb`: `/tracks/:id`

**Comment by ramyaravindranath** [comment]
PR for the issue https://github.com/exercism/x-api/pull/140.
