### ISSUE TITLE
(Swift) Hello-World testcase error

### ISSUE THREAD

**Issue by Illoric** [exercism/x-api#156]
Hello! While this is related to the entry level exercise, I'm raising this concern in case it also is mirrored across the remaining Swift exercises which I have yet to venture into. I had an issue with the test file missing the parameter reference in the function call which caused issues with the test cases themselves (i.e. hello("bob") instead of the required hello(parameter: "bob")). Once I added the parameter reference to the function call they worked fine.

Please let me know if I'm missing something here. I'm obviously new to the language :).

**Comment by mhinz** [comment]
CC @exercism/swift

**Comment by masters3d** [comment]
Swift uses enforced labels on the declaration side so if you do declare a label on the definition, the compiler will try to help you but suggesting a fix it on the call site. Just use an underscore on the definition. Skim over the swift manual. 

let me know if you have any issues on the swift repo. https://github.com/exercism/xswift/blob/master/exercises/hello-world/Sources/HelloWorldExample.swift

**Comment by kytrinyx** [comment]
@Illoric Once you figure this out, would you be willing to help suggest an improvement to the "getting started" documentation for Swift?

It lives here: https://github.com/exercism/xswift/blob/master/docs/TESTS.md
and is displayed on the site here: http://exercism.io/languages/swift/tests

**Comment by Illoric** [comment]
@masters3d Thank you! It appears I glanced over this bit of magic previously.

@kytrinyx Overall, I think the documentation was quite helpful. This "issue" could've been avoided with some further due diligence on my part :). However, I would be happy to contribute to documentation updates/improvements.

**Comment by kytrinyx** [comment]
@Illoric Excellent. If you do have suggestions or tweaks, please submit them in the xswift repository. ✨
