### ISSUE TITLE
Share test data

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#16]
Moved from exercism/exercism.io#1065, reported by @szabgab

-----

It would be nice if we could share test data files. There are a few json files in the Perl 5 exercises. they could be moved to the assignments/shared/exercisename.json
for each exercise.

Then if   assignments/shared/exercisename.json   was also included in the `exercism fetch` then they would be available for the users as well. So this ticket is asking to implement that copy mechanism.

-----

Note: The path would be `metadata/exercise.json` in this new repository.

**Comment by alexgirdler** [comment]
@kytrinyx I created a working example for ruby and will look into updating for other languages, do you mind taking a look at this and giving me any feedback on it?

[Link](https://gist.github.com/alexgirdler/4f9247ec237ae9212830)

**Comment by kytrinyx** [comment]
I'll take a closer look in a bit (I'm waiting for a meeting to begin).

Take a look at the github.com/exercism/x-common repo where we've started adding shared data, e.g. https://github.com/exercism/x-common/blob/master/bob.json

Instead of serving up the shared content, we've been writing little generators on a problem-by-problem basis in specific languages (Go primarily at the moment), and committing the result to the language track repo. (I'll update this issue with a more coherent explanation after my call).

**Comment by kytrinyx** [comment]
Ok, people are late :) I guess I'll take a stab at this now.

So... this issue is about a year old, and I failed to update it when the Go track started developing a new approach to these.

We're currently putting shared data in the x-common repo in `$SLUG.json`, so for hamming, it's `hamming.json`: https://github.com/exercism/x-common/blob/master/hamming.json

We only have a handful of these shared cases at the moment.

Then, what we've been doing is creating a little script that the track maintainers can run. It takes the json from x-common and generates a normal test suite from it.

Both the script and the test suite are committed to the repo, but the script is named `example_generator.rb` or `example_gen.rb` or something (anything with `example` in the name will be skipped when serving up files).

Does this make sense?

Do you want to take a stab at generating hamming using the shared hamming.json data?

**Comment by alexgirdler** [comment]
Yeah that makes sense. I'll look into it later today and report back.

**Comment by kytrinyx** [comment]
I'm closing this. If you ever come back to it don't hesitate to reopen it. Cheers!
