### ISSUE TITLE
Add support for fetching exercise-agnostic files

### ISSUE THREAD

**Issue by sunzenshen** [exercism/x-api#29]
A useful feature would be if `exercism fetch` could also retrieve some common files for a language track.  For example, the [xC track](https://github.com/exercism/xc/) could have a folder containing some common build files used by all the exercises.

When a user opens the "exercism/c" folder, they should see the following contents:
- hamming (the first exercise)
- vendor (this is a folder that contains files for a unit test build environment)

**Comment by ErikSchierboom** [comment]
So the idea is that there is a separate vendor folder that gets included? That will be very useful. However, I'd also really like there to be a possibility to include files in the root, which is where build files (which can be used to execute all tests) are usually located.

**Comment by kytrinyx** [comment]
Yeah, maybe there could be a way to specify in the config which files and/or directories would be included in this.

**Comment by ErikSchierboom** [comment]
I really like the option to allow us to specify the files to include in the config file.

**Comment by kytrinyx** [comment]
> However, I'd also really like there to be a possibility to include files in the root

I think that each language-specific repository should have a specific directory, I don't know what it would be called, and that directory could have subdirectories or whatever. It would take whatever is in that directory and stick it in the root.

So, e.g. in xpython:

```
.
├── LICENSE
├── README.md
├── docs/
│   ├── ABOUT.md
│   ├── ...
│   └── img
├── exercises/
│   ├── accumulate
│   ├── acronym
│   ├── ...
│   └── zebra-puzzle
├── img/
│   └── icon.png
├── global/
│   ├── some-vendored-library
│   └── subdir
│       └── other-vendored-library
└── test/
```

Does that make sense?

**Comment by kytrinyx** [comment]
To clarify, `some-vendored-libary` would end up at the root of the user's exercism/python directory, and if some language wanted to have things end up in `exercism/c/vendor/whatevs` then it would be in `xc/global/vendor/whatevs`

**Comment by kytrinyx** [comment]
Oh: I also think that the x-api endpoint should zip everything up, and the CLI should unzip it.

We have code that does something similar: https://github.com/exercism/x-api/blob/d153906782d0b77213effed06b392ae98b031295/lib/xapi/implementation.rb

**Comment by ErikSchierboom** [comment]
@kytrinyx I think having a `global` folder which contents are then put in the root makes perfect sense! It's easy to grasp and very useful. Just to be clear, any files in the root of the `global` directory would also be placed in the root?

<pre>
.
├── LICENSE
├── README.md
├── docs/
│   ├── ABOUT.md
│   ├── ...
│   └── img
├── exercises/
│   ├── accumulate
│   ├── acronym
│   ├── ...
│   └── zebra-puzzle
├── img/
│   └── icon.png
├── global/
│   ├── some-vendored-library
│   ├── subdir
│   │   └── other-vendored-library
│   └── run-tests.cmd
└── test/
</pre>

Would this result in `run-tests.cmd` being placed in the root?

I just thought of something else. You mentioned that the files in the `global` directory would be placed in the root of the language track's directory, but what if I also want files to be placed in the exercise's directory itself? I could manually add the file to each exercise in the corresponding `exercises/<name>` directory, but that becomes a bit tedious and repetitive. Maybe we could have a second folder named `global-exercise` or something like that, which contens are automatically placed in the exercise folder?

**Comment by ramyaravindranath** [comment]
@ErikSchierboom : Just wondering if you are working on implementation side ? I started looking into it. If you have already started I am happy to leave that for you :)

**Comment by ErikSchierboom** [comment]
@ramyaravindranath No I wasn't, be my guest!

**Comment by ramyaravindranath** [comment]
Thanks! @kytrinyx:  I am working on this issue.

**Comment by kytrinyx** [comment]
> Just to be clear, any files in the root of the global directory would also be placed in the root?

Yepp, that's what I was thinking. And recursively, any subdirectories.

**Comment by kytrinyx** [comment]
> what if I also want files to be placed in the exercise's directory itself?

To clarify, are you asking how to get a random `run.sh` file to get delivered to

```
exercism/python/hamming/run.sh
```

?

If so, then the way to do that is to put it in `xpython/exercises/hamming/run.sh`.

**Comment by kytrinyx** [comment]
Aaah, wait, I see what you mean. If ALL the exercises needed the same file, would there be a way to do that?

I guess we could. Has the need come up, though?

**Comment by ErikSchierboom** [comment]
@kytrinyx Come to think of it, not really. Just ignore that one. The global files will do perfectly fine!

**Comment by kytrinyx** [comment]
> The global files will do perfectly fine!

Awesome, we'll start there and see how it goes.

**Comment by rbasso** [comment]
In the Haskell track we have each exercise as a self-contained project, and this forces us to replicate configuration files.

It would be great if we could put the common files in a single folder!

From a more abstract point of view, one could think of an exercise as a **union** of a `common` and a `specific` directory structures:

```
common
├── stack.yaml
├── test/
│   ├── Spec.hs

specific
├── HINTS.md
├── package.yaml
├── src/
│   ├── LeapYear.hs
├── test/
│   ├── LeapYearSpec.hs

combined
├── HINTS.md
├── stack.yaml
├── package.yaml
├── src/
│   ├── LeapYear.hs
├── test/
│   ├── Spec.hs
│   ├── LeapYearSpec.hs
```

An **specific-biased union** would be perfect, favoring the specific content over the common one in case of conflict. :grin:

Without a feature like that, it is impossible in our current structure to factor out some common code in the the test suites. Of course, we can live without that, but it would be a very interesting feature. :smile:

An alternative - but this may not the place to discuss it - would be to allow a track-specific script to assemble the folder to be delivered to the students. This would be the ultimate flexibility...
