### ISSUE TITLE
Deliver a track-level README with onboarding instructions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#31]
@ismaild suggested that we deliver a track-level README at the root of each language track.

This would probably help on so many levels. See https://github.com/exercism/exercism.io/issues/1931 for details.

**Comment by kytrinyx** [comment]
Depends on https://github.com/exercism/x-common/issues/69 and https://github.com/exercism/x-api/issues/46

**Comment by Insti** [comment]
exercism/x-common#69 and #46 are both closed.

exercism/exercism.io#1931 has a cyclic dependency with this issue.

Can we close them both?

**Comment by kytrinyx** [comment]
This is specifically to deliver a `README.md` in the root of the exercism/TRACK_ID directory for the user when they fetch code.

We have to write code to do that.

Once https://github.com/exercism/x-api/issues/29 is completed, this issue will be trivial to complete.

We can close exercism/exercism.io#1931 in favor of this one.

**Comment by Insti** [comment]
Closed https://github.com/exercism/exercism.io/issues/1931 and adding a reminder here for another part of the task: 

kytrinyx wrote:
> Once that support is up I'll generate an issue for each separate track to write the actual README.
