### ISSUE TITLE
Expose a list of all existing problems

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#32]
This is based on the `metadata/` directory.

See https://github.com/exercism/x-common/pull/31

It would be great to have a list of which languages have implemented which problems.

**Comment by tphyahoo** [comment]
Kytrinys's Suggested approach:

1. little ruby script a la #!/usr/bin/env ruby that just figures out how to create the hash, and
2. figure out how to serve this from an api endpoint

We already have language->problem indexing (Config.find... problems)
https://github.com/exercism/x-api/blob/master/lib/app/routes/problems.rb#L9

So, for this, we could just do almost the same thing, but make it problem->language indexing.
