### ISSUE TITLE
Allow language-specific README inclusion at the problem level

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#44]
We currently have a language-specific inclusion (`SETUP.md`) that will be added to every single README in the track.

As suggested by @pminten in https://github.com/exercism/x-common/pull/67#issuecomment-89819097 we should also have the ability to include language-specific content on a problem-by-problem basis.

**Comment by etrepum** [comment]
:+1:

**Comment by kytrinyx** [comment]
I'm suggesting `HINTS.md` for this file.

The work to implement it would be:

1. Read a `HINTS.md` file and include it into the README.
1. Ignore errors if the file is missing.
1. Filter out the `HINTS.md` file when serving the exercise.

**Comment by nebkor** [comment]
This is possibly related to something I'm interested in: dynamic content in the problem READMEs regarding the exact command to execute to run the tests.  Since each problem already knows the names of its test files, all we'd need is for the README generator to know about a track-specific command for test running (eg, with Racket, the command is "raco test").

**Comment by kytrinyx** [comment]
Yepp, this would be great.

The simplest thing would be to use this to hand-code the correct command in the `HINTS.md` file.

Another approach would be to have something in `config.json` that has the test command with a placeholder, and then the generator would need to know how to replace that placeholder. I like that a bit better.

Sometimes the command might not include a path name, other times it would. I'm not sure if we can unambiguously determine what we'd need to slot into the command.

**Comment by nebkor** [comment]
Having a test command and place-holder in the config.json or similar is what I was thinking of.  I'll try to get something together that does a thing, with sane fallback defaults, and non-breaking migration path (opt-in for track owners).

**Comment by kytrinyx** [comment]
Before we start down that path, would you mind checking the various languages we have in place to see if there are any really surprising outliers? The language track pages on the site should give the test command under "running the tests" http://exercism.io/languages/clojure

**Comment by abhishekbose87** [comment]
@nebkor Have you started work on this ? If not I would like to take a shot at it.

**Comment by nebkor** [comment]
I've not had time to put to this at all, so go for it!

**Comment by abhishekbose87** [comment]
:+1:
