### ISSUE TITLE
Document API/CLI interaction 

### ISSUE THREAD

**Issue by canweriotnow** [exercism/x-api#45]
Maybe in a wiki?

I might have an edge case in writing an alternate client ([exercism-emacs](https://github.com/canweriotnow/exercism-emacs)), but in moving away from wrapping the CLI in that project to pulling JSON from the API and writing it out to files, I've had to do a lot of bouncing around between Ruby and Go source to figure out what's going on at each step... since there has been discussion on the CLI repo about new features, I was thinking that either here or there it might be nice to document for those curious, arrogant, or bored enough to write their own client the exact workflow, i.e. `exercism fetch` pulls JSON from endpoint _a_, writes from keys _b_ and _c_ to files _d and _e_ in directory `foo/bar`, creating it if it doesn't exist.

I know nobody likes writing documentation, and I'd be happy to kick it off with my own discoveries (and in the hopes that someone more familiar will correct my misapprehensions).

So, two questions:
1. Does anyone else think this is a worthwhile undertaking (and moreover, willing to help?)
2. Where should such a thing live? x-api wiki? cli wiki? somewhere else?

**Comment by kytrinyx** [comment]
Yeah, I think this would be useful, and I am uniquely situated to write the docs. I could at the very least write a quick list of the endpoints and what they do and why they're so weird (historical artifacts, I swear).

Are you familiar with any of the tools that people tend to mention when API documentation comes up?

http://www.mattsilverman.com/2013/02/tools-to-generate-beautiful-api-documentation.html

**Comment by canweriotnow** [comment]
Yeah, I've played with some of the tools mentioned... apiary is neat, but seems like duplication of effort... So far the project I like best is Swagger... I almost used it in a project at work but it didn't quite fit the project, but I have played with it... I'm not sure how well any of the projects document already-existing APIs without a lot of hand-written specification like apiary... refactoring x-api with one of the Ruby Swagger libraries might pay dividends in terms of sustainability, documentation, and eliminating "historical artifacts". 

I think that's probably beyond the scope of this issue, but I would be more than happy to take a look at the API code and see if maybe rebasing it on something self-documenting might be a feasible/worthy refactoring project.

I'm not sure how much I can help coordinate such an effort with the CLI, my Go experience is limited to one or two exercises from exercism :)

**Comment by canweriotnow** [comment]
So, as a suggestion to get started, maybe add a wiki to this repo for documentation of the *current* API, historical artifacts and all, as a basis for discussion and future iteration?

**Comment by kytrinyx** [comment]
Good plan, I'm adding the wiki now.

**Comment by canweriotnow** [comment]
So I'm playing around with [API Blueprint](https://apiblueprint.org/) which seems to be a nice agnostic way of writing Markdown API docs that can then be used for conformance testing with [Dredd::Rack](https://github.com/gonzalo-bulnes/dredd-rack), for example, in the case of Ruby. 

If it looks useful I'll throw up a branch or link to some stuff in the wiki. Just mentioning it here in case someone's been down this road and wants to scream **no, don't waste your time, consequences will never be the same** or some such.

**Comment by canweriotnow** [comment]
I just posted my first experiment with API Blueprint to Apiary... @kytrinyx I sent you an 'editor' invite, happy to transfer ownership or whatever, I'm not sure how the permissions etc. work tbh, just signed in on the free plan and started poking.

**Comment by kytrinyx** [comment]
Cool, I'll poke around with this when I get back from my trip.

**Comment by canweriotnow** [comment]
@kytrinyx when you get back, maybe we can go over go over which api calls go to x-api and which go to exercism.io, reasons for each, etc... I've got the x-api ones just about fully documented but then a bunch go to the other app, it would help to understand when/where/why things happen.

That said, hope you're having a nice trip :smiley:

**Comment by kytrinyx** [comment]
My trip has been amazing. I got over 30 PRs to exercism over the course of the conference, and it was really inspiring to be around a bunch of people who are excited about their open source projects, and willing to jump in and figure things out and improve things.

I have a half hour before I need to board the plane. I'll see about making a list of the endpoints and then I can fill things in when I have time.

**Comment by kytrinyx** [comment]
### x-api

x-api is sometimes called directly from the CLI, sometimes the exercism.io calls it to display stuff, and sometimes the CLI calls x-api who calls exercism who calls x-api back... or something. I'll untangle it all when I have a moment. Here's what I have so far:

**Assignments** DEPRECATED

These are called from older versions of the CLI.

`GET /assignments/:track` Returns all the problems for a track. I have no idea if it was actually ever called. http://x.exercism.io/assignments/ruby

`GET /assignments/:track/problem` Returns a single problem for a particular track (test suite, README, etc). Called from `$ exercism fetch` http://x.exercism.io/assignments/ruby/leap

**Demo** DEPRECATED.

Called from older versions of the CLI.

`GET /demo` Returns the first problem in each language track. http://x.exercism.io/demo

**Tracks**

`GET /tracks/:track` lists the configuration for a track (active, list of problems, where is the repo, what is the language name). It is called from `$ exercism list ruby`. http://x.exercism.io/tracks/ruby

`GET /tracks` is called from the exercism.io app to show lists of active/upcoming languages.

**Problems** WIP

 `GET /problems/demo` returns the first problem in each track. Called from `$ exercism demo`.
http://x.exercism.io/problems/demo

`GET /problems/:track` isn't called from anywhere that I can tell. We will be using it for https://github.com/exercism/exercism.io/issues/2299

`GET /problems/:track/:slug` - get a specific problem in a particular language. http://x.exercism.io/problems/ruby/leap

It's also used to check if a problem exists (from the exercism.io app).

**Exercises** WIP

This is a grab bag of stuff that has to do with a user's stuff.

**Comment by kytrinyx** [comment]
I went through all the CLI commands, and this is what I've got:

=> exercism demo
x-api:  GET /problems/demo?key=USER_KEY

=> exercism tracks
x-api: GET /tracks

=> exercism list TRACK_ID
x-api: GET /tracks/TRACK_ID

=> exercism fetch
(calls x-api, which then calls exercism.io to figure out what the user currently is working on, unless you're fetching a specific problem in a specific track)

x-api GET /v2/exercises - active stuff in all languages
x-api GET /v2/exercises/:track - active stuff in a specific track
x-api GET /v2/exercises/:track/:slug - one specific problem.

Also calls:
exercism.io: GET /api/v1/exercises?key=USER_KEY to get a list of all the user's exercises

=> exercism restore
x-api: GET /v2/exercises/restore - calls exercism.io /api/v1/iterations/latest
(note that the current CLI actually calls an endpoint in exercism which proxies to this endpoint. I've fixed that in master and the next release will talk directly to x-api).

=> exercism open
exercism.io: GET /api/v1/submissions/TRACK_ID/SLUG?key=USER_KEY - given the track and slug, return info, including canonical url.

=> exercism download
exercism.io: GET /api/v1/submissions/UUID - gets a specific submission by the submission uuid

=> exercism submit
exercism.io: POST /api/v1/user/assignments

=> exercism unsubmit
exercism.io: DELETE /api/v1/user/assignments?key=USER_KEY

=> exercism skip TRACK_ID SLUG
exercism.io: POST /api/v1/iterations/TRACK_ID/SLUG/skip?key=USER_KEY

**Comment by canweriotnow** [comment]
@kytrinyx that's awesome - I had the x.exercism.io endpoints but hadn't gone into the exercism.io endpoints. I wanted to see if I could get some insight into the reasoning for dividing into x.exercism.io (x-api) and exercism.io (exercsim.io) API hosts/codebases... historical reasons? Deliberate separation of concerns? 

If the former, any desire/wish/plan to merge the two into a single API? I'm happy to help with whatever... also avaialble to chat on gitter or irc or whatever if that might be a more useful format for that conversation.

**Comment by kytrinyx** [comment]
The separation is kind of deliberate... I like having all the problems live in a completely isolated API, which means that anything that is purely about fetching problems can go to x.exercism.io. The dirty side of the coin is that now anything to do with submitting/knowing what a user has done has to go to the exercism.io API. Maybe one should proxy requests to the other, or a third app should proxy to both :/

**Comment by ben-biddington** [comment]
@canweriotnow there is also [gauge](http://getgauge.io/)
