### ISSUE TITLE
Serve language-specific documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#46]
See https://github.com/exercism/x-common/issues/69

Implementation steps:

- create some simple files in the test fixtures

Suggested files:

`./test/fixtures/problems/fake/docs/`

- `INSTALLATION.md`
- `WORKFLOW.md`
- `HELLO.md`
- `TOOLS.md`
- `RESOURCES.md`

The endpoints should probably go into a new file `lib/app/routes/docs.rb`, and the endpoint would be:

```
GET /docs/:track
```

It would return a JSON object with a key for each file.

**Comment by groyoh** [comment]
This issue should be closed :wink:

**Comment by kytrinyx** [comment]
Yes, it should :) Thanks!

Also, I need to open one that has to do with figuring out how to serve images.
