### ISSUE TITLE
Expose list of problems that have yet to be ported for a language track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#48]
The [`/problems`](http://x.exercism.io/problems ) endpoint already lists the problems and which languages _have_ implemented them: -- let's add the list of languages that have not implemented them.

In addition, we should add a "todo" key to the language track endpoint itself that lists problems that have yet to be implemented.

If a problem is deprecated or foregone (see the config.json for each language), it should not go in the list.

**Comment by kytrinyx** [comment]
I'm going to be working through this with @jendiamond @kalisafalzone @ashlopez

**Comment by KalisaFalzone** [comment]
Thanks for showing us everything last night, Katrina. I learned so much! We are close to completing the todo list for each track (aka #14).

**Comment by kytrinyx** [comment]
It was great working with you, see you next week.

**Comment by jendiamond** [comment]
@KalisaFalzone and I worked together to create methods out of our sketch from the other night.

I created a Todo class and renamed and re-factored some of the methods.

-----
### Create Todo class methods to access tracks and slugs

+ slugs are the exercises that are written in each language
+ track are the languages

#### Methods:
=====
##### `get_slugs`
    gets a list of all the unique exercises that currently exist in all the language tracks
=====
##### `get_tracks`
    gets a list of all the language tracks
=====
##### `get_existing_slugs(track)`
    gets a list of all the exercises that currently exist in a particular language track      
=====
##### `get_todo(track)`
    gets a list of all the exercises that need to be written for a language track to have  
      all of the exercises that currently exist between all the tracks
=====
##### `print_todo(track)`
    print a list of number of exercises that need to be written for a language track to  
      have all of the exercises that currently exist between all the tracks
=====
##### `track1_minus_track2(track1, track2)`
    gets a list of all the exercises that currently exist in a particular language track

**Comment by kytrinyx** [comment]
The API does not have a command-line, so that method should be omitted.

> track1_minus_track2(track1, track2)

I'm not sure what this means. Are we comparing, say, Python to Ruby? If so, why? What does that have to do with TODOs?

> get_todo(track)

In Ruby we very rarely use `get_` in names.

How about reversing this? We already have a `Track` object. What if we could ask it what, out of a particular list of slugs, remained to be done?

**Comment by kytrinyx** [comment]
This was completed.
