### ISSUE TITLE
Figure out how to serve images for language-specific documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#53]
The `problems/$LANGUAGE/docs/` directory optionally contains an `img` directory (e.g. https://github.com/exercism/xfsharp/tree/654e63a6b31eac2991b64a181c87974c52852d3e/docs/img). We need to figure out how to serve these as actual images from the API (or, I suppose elsewhere, but the API would be my first choice for the sake of simplicity).

Can we expose the `img/` directories as static in Sinatra?

See https://github.com/exercism/rossconf/issues/11 and https://github.com/exercism/x-api/issues/46 for context.

**Comment by groyoh** [comment]
I assume something like this could work:
```ruby
get '/docs/:track/img/:filename' do |track, filename|
  path = "./problems/#{track}/docs/img/#{filename}"
  type =  File.extname(path)
  send_file path, type: type if File.exist? path
end   
```
but I don't have much experience about sending images through Sinatra. There might be a better solution.

**Comment by kytrinyx** [comment]
Oh, right. `send_file`... totally forgot about this. I think this will do nicely.

**Comment by kytrinyx** [comment]
We would need to handle the 404 case, which would require an explicit else.

Also, I took a closer look at `send_file`, and from the code it looks like it sets the content type based on the filename of the extension, defaulting to `application/octet-stream`, which seems fine.

So that would change the above to something like:

```
      get '/docs/:track/img/:filename' do |track, filename|
        path = File.expand_path(File.join(Xapi::Config.path,track, 'docs', 'img', filename))
        if File.exist? path
          send_file path
        else
          halt 404, {error: "Not found."}.to_json
        end
      end
```

Or something. Provided that I've got the file path stuff right.

**Comment by groyoh** [comment]
It looks to me that `send_file` sets content type only if it is not already set. And since the `Core` class sets it to `application/json;charset=utf-8`, it will not change unless you specify it explicitely.

**Comment by kytrinyx** [comment]
Yeah, I just discovered that. Also, setting the content type to `File.extname` isn't going to work, since there's no content-type `.png`. `File.extname(path).sub('.', '').to_sym` would work, though.

**Comment by groyoh** [comment]
Using `File.extname` worked for me locally :wink: That's why I wrote it, but maybe we are not using the same versions.

**Comment by kytrinyx** [comment]
Ah, let me make sure I'm using the most recent version of Sinatra. Probably not, now that I think about it. We just released a new version for the first time in a year, and I probably forgot to upgrade.

**Comment by groyoh** [comment]
Any news on this?

**Comment by kytrinyx** [comment]
Sorry, I've been swamped and haven't gotten to this yet. I've got some time blocked out to work on exercism tonight and will look at it then.

**Comment by groyoh** [comment]
No worry! :wink: Just wanted to make sure that this issue does not get lost. Ahah, in the meantime I've been looking a bit at #41 and I might work on it soon. :smile:

**Comment by kytrinyx** [comment]
Cool! So yes: Sinatra was pinned at an older version. I'm updating that now.

**Comment by kytrinyx** [comment]
I talked to @canweriotnow - and he suggested that we should base64encode the images, which I think is the right move.

**Comment by kytrinyx** [comment]
@GustavoCaso are you still looking for issues to work on? If so, would this one be interesting to you? Getting this fixed would unlock a whole bunch of other issues that could be fixed (in particular, some interesting improvements to the languages pages on the site).

**Comment by GustavoCaso** [comment]
Sure @kytrinyx I will have a look at this one

**Comment by GustavoCaso** [comment]
@kytrinyx Do you want another endpoint for this case ?? Is for `v1` or `v3, ` could we use the `Xapi::Doc` to handle the looking for images? I guess that you want just one endpoint for all tracks related stuff isn't it

**Comment by kytrinyx** [comment]
I'd like another endpoint for this, yes, in `v3`.

I'm thinking:

```
GET /tracks/:id/docs/img/$IMAGE_FILE_NAME
```

> I guess that you want just one endpoint for all tracks related stuff isn't it

I'm not sure what you mean.

**Comment by GustavoCaso** [comment]
> I guess that you want just one endpoint for all tracks related stuff isn't it

I mean that all the information of the tracks page is done by just one endpoint

**Comment by kytrinyx** [comment]
Oh, right. Yes, in a sense--but the images are going to be referenced as URLs, so the browser will go get them. It's fine to make this a separate endpoint.

**Comment by GustavoCaso** [comment]
Great I see. Well when I get home I will work on this one and keep updating the `docs`if there are other endpoint that you want me to help you just let me know. :smile:

**Comment by kytrinyx** [comment]
Awesome! Today I have much more time on my hands, so I will make a bunch of progress on the docs. Yesterday I had meetings back to back almost the whole day.

**Comment by GustavoCaso** [comment]
Great to hear that. Yes I know that feeling :bookmark_tabs:

**Comment by GustavoCaso** [comment]
@kytrinyx I wanted to ask you we actually want to show a link to the image that when the user clicks it, it download it or   want to show the image in the actual language page ?

**Comment by GustavoCaso** [comment]
Sorry if I make so many questions @kytrinyx

**Comment by kytrinyx** [comment]
I want to show the actual image in the page.

**Comment by GustavoCaso** [comment]
ok @kytrinyx sounds great.
