### ISSUE TITLE
bin/fetch-configlet fails on syntax error on pre-4.0 bash shells

### ISSUE THREAD

**Issue by jtigger** [exercism/x-api#59]
```
$ git clone git@github.com:exercism/xjava.git
$ cd xjava
$ bin/fetch-configlet 
bin/fetch-configlet: command substitution: line 9: syntax error near unexpected token `newline'
bin/fetch-configlet: command substitution: line 9: `    Darwin*'
bin/fetch-configlet: line 8: syntax error near unexpected token `;;'
bin/fetch-configlet: line 8: `        echo "mac";;'
```

As lovingly detailed [here](http://www.in-ulm.de/~mascheck/various/cmd-subst/), omitting the optional leading paren in a `case` statement within a command substitution — `$( )` — fails to parse in pre-4.0 bash shells.

Despite the fact that Bash 4.0 was released in 2009, stock bash on even the latest OS X is 3.2. :(

This is clearly not a huge deal — the Mac-based contributor can simply fix the script to work with their shell, but if fixed, it's a smoother ride.

**Comment by jtigger** [comment]
@kytrinyx, time for the magic scripts :) — please replicate across tracks.

**Comment by kytrinyx** [comment]
@jtigger I'm on it! I have to get home to my personal computer to get access to my collection of shims and tricks, but I'll get this sorted this weekend.

Thanks for the detailed fix!

**Comment by kytrinyx** [comment]
Fixed!
