### ISSUE TITLE
base encode file contents

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#64]
See https://github.com/exercism/x-api/issues/63

This is going to be a bit complicated.

- We need to rewrite part of the CLI to handle the encoded files.
- We should serve both the new and the old versions, so that old versions of the  CLI will still work.
- If a problem has files with invalid utf-8 characters, then we should not serve it un-encoded, and rather serve up a single "readme" that says: please upgrade your CLI. That way old CLIs will write out the README, and new CLIs will write out the actual problem.

**Comment by GustavoCaso** [comment]
@kytrinyx is anyone working on this one, if not I'll grab this one

**Comment by kytrinyx** [comment]
Rather than base64 encoding the contents, I think we should zip it all up, per the discussion in #75 (see: **Content-Type: application/octet-stream**).

Thoughts?

**Comment by GustavoCaso** [comment]
@kytrinyx sound great about zip it and serving. If everything ok I can start with this one

**Comment by kytrinyx** [comment]
Yeah, definitely! Thank you.

**Comment by GustavoCaso** [comment]
@kytrinyx You want to download the zip file when hitting this endpoint ?

**Comment by GustavoCaso** [comment]
@kytrinyx just an opinion. Should be the content-type `application/zip` ?

**Comment by kytrinyx** [comment]
Probably. I didn't do my homework on this one. Would you mind taking a look to see if you can find a good reference that says which it should be?

**Comment by GustavoCaso** [comment]
@kytrinyx Are we going to continue with this one ??

**Comment by kytrinyx** [comment]
Zipping was implemented, right?

**Comment by GustavoCaso** [comment]
@kytrinyx yes it was implemeted

**Comment by kytrinyx** [comment]
Yeah, then this is done. Thanks!
