### ISSUE TITLE
Add "about language" documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#65]
See https://github.com/exercism/exercism.io/issues/2299#issuecomment-123798119
/cc @mixolidia @sguermond

Each language track should optionally contain a file `docs/ABOUT.md`, which can contain the short intro to the language.

This might be enough to return an "about" key from the endpoint defined in `lib/app/routes/docs.rb`: http://x.exercism.io/docs/ruby

To do this, we'll need to add an `ABOUT.md` file to `test/fixtures/problems/fake/docs/` and then work in these files:

- `lib/xapi/docs.rb`
- `test/xapi/docs_test.rb`

**Comment by mixolidia** [comment]
Thanks!
