### ISSUE TITLE
an internal server error was received

### ISSUE THREAD

**Issue by mscottreed** [exercism/x-api#67]
C:\Exercism\python>exercism submit luhn\luhn.py

Submitted Luhn in Python.
Your submission can be found online at http://exercism.io/submissions/9a010455bf
5444298d3c1102bab4670c

To get the next exercise, run "exercism fetch" again.

C:\Exercism\python>exercism fetch

Not Submitted:                  26 problems
clojure (Bob)                   C:\Exercism\clojure\bob
coffeescript (Hello World)      C:\Exercism\coffeescript\hello-world
cpp (Bob)                       C:\Exercism\cpp\bob
csharp (Leap)                   C:\Exercism\csharp\leap
elisp (Hello World)             C:\Exercism\elisp\hello-world
elixir (Bob)                    C:\Exercism\elixir\bob
erlang (Leap)                   C:\Exercism\erlang\leap
fsharp (Sum Of Multiples)       C:\Exercism\fsharp\sum-of-multiples
go (Leap)                       C:\Exercism\go\leap
haskell (Leap)                  C:\Exercism\haskell\leap
java (Etl)                      C:\Exercism\java\etl
javascript (Hello World)        C:\Exercism\javascript\hello-world
lfe (Leap)                      C:\Exercism\lfe\leap
lisp (Point Mutations)          C:\Exercism\lisp\point-mutations
lua (Hello World)               C:\Exercism\lua\hello-world
objective-c (Hello World)       C:\Exercism\objective-c\hello-world
ocaml (Bob)                     C:\Exercism\ocaml\bob
perl5 (Bob)                     C:\Exercism\perl5\bob
php (Hamming)                   C:\Exercism\php\hamming
plsql (Hamming)                 C:\Exercism\plsql\hamming
python (Etl)                    C:\Exercism\python\etl
ruby (Hello World)              C:\Exercism\ruby\hello-world
rust (Leap)                     C:\Exercism\rust\leap
scala (Hello World)             C:\Exercism\scala\hello-world
scheme (Hello World)            C:\Exercism\scheme\hello-world
swift (Leap)                    C:\Exercism\swift\leap

New:                            1 problem
python (Etl)                    C:\Exercism\python\etl

unchanged: 47, updated: 0, new: 1

C:\Exercism\python>exercism skip python etl
Exercise "etl" in "python" has been skipped.

C:\Exercism\python>exercism fetch
2015/08/09 10:33:13 an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://githu
b.com/exercism/x-api/issues

C:\Exercism\python>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.0
Exercism CLI Latest Release: 2.2.0
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\Scott
Config file: C:\Users\Scott\.exercism.json
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: C:\Exercism

If you are having trouble and need to file a GitHub issue (https://github.com/ex
ercism/exercism.io/issues) please include this information (except your API key.
 Keep that private).

**Comment by kytrinyx** [comment]
Thanks for reporting this, I'll look into it today.

**Comment by kytrinyx** [comment]
You mentioned (privately) that explicitly fetching the next exercise worked. After that happened, were you still getting the error if you say `exercism fetch`? How about if you just said `exercism fetch python`?

I fixed a problem in the API today that may have been causing this error (there was a problem with an incorrect symlink in one of the other tracks. This would have affected the `exercism fetch` command, but not the `exercism fetch python` command).

**Comment by mscottreed** [comment]
Yes, exercism fetch python worked/works.  So you probably nailed it.

 

Thanks again
