### ISSUE TITLE
Internal server error during fetch language which does not exist

### ISSUE THREAD

**Issue by alex-bender** [exercism/x-api#71]
```
$ exercism fetch A
2015/10/07 17:54:23 an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/x-api/issues 
```

**Comment by kytrinyx** [comment]
We can definitely do better with that error! Thanks.

**Comment by kytrinyx** [comment]
Deploying a fix now.

**Comment by alex-bender** [comment]
Thanks

**Comment by alex-bender** [comment]
Seems that error still exists. But in other manner:
```
 ✘ alex@bender > ~/ > exercism f c
2015/10/08 14:57:35 an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/x-api/issues 
 ✘ alex@bender > ~/ > exercism f clang
2015/10/08 14:57:37 unable to fetch problems (HTTP: 400) - no language track 'clang'
 ✘ alex@bender > ~/ > 
```
btw, how can I fetch problems for `C`?

**Comment by kytrinyx** [comment]
C isn't an active track yet, but it's possible to fetch individual exercises for tracks that haven't been launched yet.

Thanks for uncovering these bugs, btw! These are things that we didn't have tests for.

**Comment by kytrinyx** [comment]
Hm. The issue in the C track is non-utf-8 characters in one of the problems.

**Comment by kytrinyx** [comment]
OK, I've narrowed the problem down and we will fix it in the C repo https://github.com/exercism/xc/issues/16

I'm going to close this again, but if you see any other weird errors, please holler!

**Comment by alex-bender** [comment]
I will.

**Comment by kytrinyx** [comment]
This should be fixed, btw. It might now be possible to get results with `exercism fetch c`.

**Comment by alex-bender** [comment]
Thanks, it is works.
