### ISSUE TITLE
Implement v3 of the API

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#75]
I've moved the Sinatra app into `v1.rb` with related code in `v1/`.

It's time to implement a second version of the API, which can be a bit cleaner with respect to terminology and payloads. Also, this version of the API will not know anything about authenticating users (exercism API keys). The endpoints are all going to be public.

We will be implementing a new API that for now will run on exercism.com/api/v2/

This API is partially described in https://github.com/exercism/exercism.io/issues/2607

The CLI will no longer talk directly to the x-api, the new exercism api will make requests to the x-api and either just forward the response, or transform things in certain ways where necessary.

We will support two different content types, though not really for all the endpoints. It's still a bit weird that some endpoints are authenticated and some are not, but I think it's okay.

I think that there are two top level resources in the first pass: `/tracks` and `/problems`. Also, there are `/exercises` which will always be nested under a track.

The `/problems` are metadata, independent of tracks. In addition to the usual metadata, it would also contain two lists: ids of tracks that have implemented the problem as an exercise, and ids of tracks that are waiting to implement them ("todos").

We will need the following endpoints, to start out with.

**Content-Type: application/json**

- [x] `GET /tracks` - metadata about all the tracks, including a list of the exercise slugs in each track.
- [x] `GET /tracks/:id` - one of the above
- [x] `GET /tracks/:id/exercises/:slug/readme`
- [x] `GET /tracks/:id/exercises/:slug/tests`
- [x] `GET /tracks/:id/exercises/:slug/exists`

**Content-Type: application/octet-stream**

- `GET /tracks/:id/exercises/:slug` - a zip containing all the files for the exercise, including a `.metadata.json` that has the language, track id, and other track information that we need.

**Comment by GustavoCaso** [comment]
@kytrinyx Is anyone helping you with this task ??

**Comment by kytrinyx** [comment]
Not yet, would you be interested in helping out?

**Comment by GustavoCaso** [comment]
Of course @kytrinyx I'll very happy helping out with this one. Don't hesitate of including me in any issue you want to solve.

**Comment by kytrinyx** [comment]
Excellent! I'm doing an experiment right now with one of the places that will consume the new API, and will know more later today.

**Comment by GustavoCaso** [comment]
Great @kytrinyx I will wait for your response I the mind time I will continue working on the other issues

**Comment by kytrinyx** [comment]
OK, my experiment basically showed me I need to try something else. I'll update you when I know more.

**Comment by GustavoCaso** [comment]
@kytrinyx Sorry to hear. If there anything I can do to help let me know.

**Comment by kytrinyx** [comment]
I did a new experiment this morning, and I've figured out a way forward. I should have a proper update later today with an actual plan for moving forward.

**Comment by GustavoCaso** [comment]
Great to hear @kytrinyx I will wait for the plan

**Comment by kytrinyx** [comment]
OK, I've pushed up a commit that has a new `v3.rb` file and a `v3/` directory where the new API lives. I've implemented `/tracks` and `/tracks/:id`.

I'm working on re-implementing the `languages/:id` endpoint to use the new API over in the exercism.io repository.

The plan is to slowly re-implement any of the endpoints in exercism.io that call the x-api, cleaning up the codebase as we go.

A simple one to get warmed up would be the README endpoint:
http://exercism.io/exercises/:track_id/:exercise_slug/readme

Want to take that one? Then we're going to need to map out some of the rewrites necessary in the exercism.io api that will use these new endpoints.

**Comment by GustavoCaso** [comment]
sure @kytrinyx I'll be happy to take it

**Comment by kytrinyx** [comment]
For now just implement the endpoint here in x-api... I'll give you a heads up once some of the refactorings in the exercism.io codebase have started (should be later today).

**Comment by GustavoCaso** [comment]
Ok sure no problem. Thanks

**Comment by kytrinyx** [comment]
@GustavoCaso once you've finished what you're working on, do you want to take a stab at implementing `GET /tracks/:id/tests`?

It should include any of the files that match the `test_pattern` in the language's config. I think we might currently have a bug and it only grabs the last one that matches the pattern.

What we should have is a hash of content (like we do with docs: `{ filename1 => contents, filename2 => contents }`.

**Comment by GustavoCaso** [comment]
@kytrinyx Sure no problem. Sounds great thing. I hope to finish with the one related to image quickly.

**Comment by kytrinyx** [comment]
This is done.
