### ISSUE TITLE
Expose list of "todos" in problems/:slug endpoint

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#76]
We've done a list of todos per language (/tracks/:id), but it would be useful to have the inverse, as well.

**Comment by behrtam** [comment]
The `todo` endpoint contains exercises that are marked as "deprecated" or "foregone" in the `config.json`.

**Comment by kytrinyx** [comment]
Ah, yepp. You're right, we need to filter those out.

**Comment by kytrinyx** [comment]
The deprecated/foregone problems are filtered out as of 83cc2193012cf30a0c9ef8fafc3f04d5d8b33a85

We still need to add the todos in the problem, though.

**Comment by IanWhitney** [comment]
@kytrinyx Maybe I'm mis-reading this issue, but I'm still seeing a deprecated problem here

http://x.exercism.io/tracks/rust

My understanding is that [Accumulate is deprecated](https://github.com/exercism/x-common/issues/129), but I still see it as a todo for Rust.

**Comment by kytrinyx** [comment]
Rust doesn't have any deprecated problems: https://github.com/exercism/xrust/blob/master/config.json#L39-L41

**Comment by IanWhitney** [comment]
Ah! We deprecate them by track. I did not get that at all. 

If Accumulate is deprecated, should we create an issue for all tracks asking them to deprecate it?

**Comment by kytrinyx** [comment]
I read through that thread recently, and it didn't feel like we had all come to a conclusion. Once I can figure out what the consensus is I'll submit an issue everywhere.

**Comment by kytrinyx** [comment]
I've asked about posting to all the tracks about deprecating accumulate. https://github.com/exercism/x-common/issues/129#issuecomment-245139276

I believe this issue is taken care of.
