### ISSUE TITLE
Skeleton files should be included in all problems to make it easier

### ISSUE THREAD

**Issue by gytdau** [exercism/x-api#82]
I'm on the Python section, and I've found that only a few challenges include a skeleton file. This is helpful, since you can then start coding without the delay of creating your own file. Example: the Bob challenge comes with bob.py:
```
#
# Skeleton file for the Python "Bob" exercise.
#


def hey(what):
    
    return
```

It'd be great if a skeleton file like this was included in all of the challenges, to make things just a little bit easier for everyone.

**Comment by gytdau** [comment]
On further inspection, this is completely the wrong repo to add an issue to. Sorry about that - I've added this issue to the correct repository.

**Comment by kytrinyx** [comment]
Thanks!
