### ISSUE TITLE
Filter out foregone/deprecated problems in "todo" lists

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#88]
The "todo" key gives us a list of exercises that have not yet been implemented in the given track.

The bug is in the `todo` method in `lib/xapi/track.rb`. Since this class is already reading the config, it should be an easy fix to exclude the deprecated and foregon exercises.

**Comment by groyoh** [comment]
@kytrinyx I think this issue was resolved by #91

**Comment by kytrinyx** [comment]
Yepp, good catch. Thanks.
