### ISSUE TITLE
Implement a more fleshed out "todo"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#94]
I think it would be useful to implement `/v3/tracks/:id/todo`.

This would have a list of problems that have not been implemented in that language track. For each problem, include:
- the list of languages that have implemented it, with a link to that exercise in their repository (to make it easy to go look at their implementation / test suites).
- the contents of the `:slug.md`, `:slug.yml`, and `:slug.json` file (if it exists)

**Comment by bmulvihill** [comment]
@kytrinyx how does one determine all the available problems?  Does that come from x-common?

**Comment by kytrinyx** [comment]
Yeah, x-common has a total list of problems. We should probably do something to list deprecated problems (at the moment I think that's beer-song and point-mutations, there might be more).

**Comment by kytrinyx** [comment]
Fixed in #98
