### ISSUE TITLE
Expose "test pattern" from config in track data

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-api#95]
We use the `test_pattern` to figure out which file has the test suite in it, in order to show it on the `exercises/:track_id/:slug/test-suite` page. E.g. http://exercism.io/exercises/javascript/leap/test-suite

The CLI also needs to have this data in order to be able to warn the user against submitting the tests instead of the solution.

Many languages use `/test/i` somewhere in the filename for tests (e.g. `leap_test.rb` in Ruby, or `BowlingTest.cs` in C#). But some languages do not. For example, JavaScript has `bob.spec.js`.

So for these languages we have a line in the config.json file that explains how to figure out if a file is a test file or not: https://github.com/exercism/xjavascript/blob/master/config.json#L6

The `Track` object has a `test_pattern` https://github.com/exercism/x-api/blob/master/lib/xapi/track.rb#L65-L71 but we don't expose this via the API yet.

For the CLI to be able to use it, we need this value in the payload from the API for the following endpoints.

- `/tracks`
- `/tracks/:track_id`
- `/v3/tracks`
- `/v3/tracks/:track_id`

**Comment by ramyaravindranath** [comment]
@kytrinyx I am looking into this.

**Comment by kytrinyx** [comment]
Thanks!
